---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---

## Loading and preprocessing the data
```{r echo=TRUE}
# Loading libraties (supressing loading output messages)
suppressMessages(library(plyr))
suppressMessages(library(dplyr))
suppressMessages(library(lattice))
suppressMessages(library(knitr))

# Compressed file Name
zfName <- "activity.zip"

# Data File Name
fName <- "activity.csv"

# Open a connection to the Compressed File / Data File
zFile <- unz(zfName, fName)

# Read Data File
fData <- read.csv(zFile)
  
# Converting date column to date Date Type  
fData <- mutate(fData, date=as.Date(date)) %>% arrange(date, steps)

# Order by date
fData <- arrange(fData, date, interval)

# Close connection
# close(zFile)
```

```{r echo=TRUE}
# Dump existing data
summary(fData)
```


## What is mean total number of steps taken per day?
```{r echo=TRUE}
fData %>% 
  filter(!is.na(steps)) %>%
  group_by(date) %>% 
  summarise(
    Mean=mean(steps), 
    Median=median(steps), 
    Total = sum(steps)
  ) -> totalStepsByDate

hist(totalStepsByDate$Total, main = "Total for Daily Step", col=rgb(1,0,0), xlab="Total Number of Steps")
```
```{r echo=TRUE}
kable(totalStepsByDate,
      caption = "Per Daily Data")
```

```{r echo=TRUE}
median(totalStepsByDate$Total)
mean(totalStepsByDate$Total)
```

## What is the average daily activity pattern?
```{r echo=TRUE}
fData %>% 
  filter(!is.na(steps)) %>%
  group_by(interval) %>% 
  summarise(
    Mean=mean(steps), 
    Median=median(steps), 
    Total = sum(steps),
    count=n()
  ) -> totalStepsByInterval

plot(
  totalStepsByInterval$interval,
  totalStepsByInterval$Mean,
  type = "l",
  xlab = "5 Minutes Interval",
  ylab = "Averaged Number of Steps",
  main = "Daily Activity Pattern",
  col = rgb(1,0,0))

maxSteps <- max(totalStepsByInterval$Mean)
maxInterval <- totalStepsByInterval[totalStepsByInterval$Mean == maxSteps,1]

abline(v=maxInterval, lwd=2, lty=2, col = 'green')
abline(h=maxSteps, lwd=2, lty=2, col = 'green')

text(maxInterval, 
     maxSteps, 
     paste("Max steps",round(maxSteps),"at interval",maxInterval), 
     cex = 0.75, offset = 1,
     pos=4)

```
  
### Interval with the maximum number of steps: 
```{r}
totalStepsByInterval[totalStepsByInterval$Mean == max(totalStepsByInterval$Mean),]
```

## Imputing missing values

### Number of NAs
```{r echo=TRUE}
length(fData$steps[is.na(fData$steps)])
```

### Locate NA's
```{r echo=TRUE}
fData %>% 
  group_by(date) %>% 
  summarise(
    isNA=is.na(mean(steps))
  ) -> naSteps

plot(naSteps$date,naSteps$isNA, pch=16, xlab = "Date",ylab = "isNA?",yaxt="n")
axis(2, at=c(0,1), lab=c("True","False"))
```

### NA Days
```{r echo=TRUE}
kable(naSteps[naSteps$isNA,])
```

```{r echo=TRUE}

### The missing data will be filled with the mean of the step number for the entire sample (without missing data)
fixedData <- fData
fixedData$steps[is.na(fixedData$steps)] <- mean(fData$steps, na.rm = TRUE)

fixedData %>% 
  group_by(date) %>% 
  summarise(
    Total = sum(steps) ) -> fixedSteps

hist(fixedSteps$Total, main = "Total for Daily Step", col=rgb(1,0,0), xlab="Total Number of Steps")

median(totalStepsByDate$Total)  # With missing values
median(fixedSteps$Total)        # Without missing values

mean(totalStepsByDate$Total)    # With missing values
mean(fixedSteps$Total)          # With out missing values

```

## Are there differences in activity patterns between weekdays and weekends?

```{r echo=TRUE}

fixedData %>% 
  mutate(Workday=format(date, "%u") <6) %>%
  mutate(dType="Workday") -> workdayDecoratedFixedSteps

workdayDecoratedFixedSteps[!workdayDecoratedFixedSteps$Workday,]$dType <- "Weekend"

workdayDecoratedFixedSteps <- mutate(workdayDecoratedFixedSteps, Workday = dType)
workdayDecoratedFixedSteps$dType <- NULL

workdayDecoratedFixedSteps %>% 
  group_by(interval,Workday) %>%
  summarise(
    Mean=mean(steps) ) -> workdayDecoratedFixedStepsByInterval

xyplot(
  workdayDecoratedFixedStepsByInterval$Mean ~ workdayDecoratedFixedStepsByInterval$interval
  | workdayDecoratedFixedStepsByInterval$Workday, 
    type="l", 
    layout=c(1,2),
    xlab="Interval",
    ylab="Steps"
  )

```